import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/layout"; // Correct the case of "Layout" import
import pp2 from "../../public/images/profile/pp2.png";
import Link from "next/link";
import { motion } from "framer-motion";
import { LinkArrow } from "@/components/icons";
import Transitionku from "@/components/Transition";

export default function Home() {
  return (
    <>
      <Head>
        <title>VincentLeonPorto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitionku />
      <main className="flex flex-col items-center justify-center min-h-screen">
        <Layout className="pt-0">
          <div className="flex flex-col-reverse sm:flex-row items-center justify-center">
            {/* Text column */}
            <div className="w-full sm:w-1/2 text-center sm:text-left">
              <motion.div
                initial={{ opacity: 0.3, y: -100 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, bounce: 0.3 }}
                whileHover={{
                  scale: 1.1,
                  boxShadow: "0px 0px 8px rgb(255, 255, 255)",
                }}
              >
                <h1 className="text-3xl sm:text-7xl font-bold text-gray-800 mb-2 text-center sm:text-left">
                  Hello, I'm Vincent Leon!
                </h1>
                <p className="text-gray-600 font-medium text-base">
                  A fourth-year undergraduate pursuing a degree in Electrical
                  Engineering and Computer Science at National Tsinghua
                  University. As I approach the culmination of my academic
                  journey, I am thrilled to present this portfolio, which
                  encapsulates my growth, passion, and dedication to the field
                  of EECS.
                </p>
              </motion.div>

              <div className="flex flex-col sm:flex-row items-center self-start mt-4">
                <Link
                  href="/dummy.pdf"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark transition duration-300 ease-in-out mb-2 sm:mb-0 sm:mr-4"
                  download={true}
                >
                  Resume <LinkArrow className="w-5 ml-1" />
                </Link>
                <Link
                  href="/Contactme"
                  className="flex items-center text-dark p-2.5 px-6 rounded-lg text-lg font-semibold underline"
                >
                  Contact
                </Link>
              </div>
            </div>

            {/* Profile picture column */}
            <motion.div
              className="w-full sm:w-1/2 mb-4 sm:mb-0 flex items-center justify-center"
              initial={{ opacity: 0.3, x: -100 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, bounce: 0.3 }}
              whileTap={{ scale: 0.9 }}
            >
              <Image
                src={pp2}
                alt="ProfilePic"
                className="w-3/4 h-auto md:w-full"
              />
            </motion.div>
          </div>
        </Layout>
      </main>
    </>
  );
}
